package com.sebas.springboot.backend.cine.entidades;
// Generated 24 abr 2023 17:34:46 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

/**
 * Tematicas generated by hbm2java
 */
@Entity
@Table(name = "tematicas", schema = "public")
public class Tematicas implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int codigo;
	private String descripcion;
	private Set<Peliculas> peliculases = new HashSet<Peliculas>(0);

	public Tematicas() {
	}

	public Tematicas(int codigo) {
		this.codigo = codigo;
	}

	public Tematicas(int codigo, String descripcion, Set<Peliculas> peliculases) {
		this.codigo = codigo;
		this.descripcion = descripcion;
		this.peliculases = peliculases;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY) 
	@Column(name = "codigo", unique = true, nullable = false)
	public int getCodigo() {
		return this.codigo;
	}

	public void setCodigo(int codigo) {
		this.codigo = codigo;
	}

	@Column(name = "descripcion", length = 50)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tematicas")
	public Set<Peliculas> getPeliculases() {
		return this.peliculases;
	}

	public void setPeliculases(Set<Peliculas> peliculases) {
		this.peliculases = peliculases;
	}

}
